version: "3.9"

services:

  worker:
    build:
      context: ./folder_worker
    image: wine_worker_image
    container_name: wine_worker
    volumes:
      - ./folder_worker:/app
    command: python worker.py
    depends_on:
      - broker
      - rabbitmq
      - model
      - database
    env_file:
      - .env

      
  # worker:
  #   build:
  #     context: ./folder_broker
  #   image: wine_worker_image
  #   container_name: wine_worker
  #   volumes:
  #     - ./folder_broker:/app
  #   command: python worker.py
  #   depends_on:
  #     - broker
  #     - rabbitmq
  #     - model
  #     - database
  #   env_file:
  #     - .env



  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: wine_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  database:
    build:
      context: ./folder_database
    image: database_image
    container_name: database_container
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./folder_database:/app
    depends_on:
      - model
    env_file:
      - .env

  broker:
    build:
      context: ./folder_broker
    image: broker_image
    container_name: broker_container
    ports:
      - "3000:3000"
    command: uvicorn app:app --host 0.0.0.0 --reload --port 3000
    volumes:
      - ./folder_broker:/app
    depends_on:
      - database
      - model
    env_file:
      - .env

  model:
    build:
      context: ./folder_model
    image: model_server_image
    container_name: model_container
    ports:
      - "5000:5000"
    volumes:
      - ./folder_model:/app
    env_file:
      - .env
    # command: >
    #   mlflow models serve -m /app/model -h 0.0.0.0 -p 5000 --env-manager=local
