version: "3.9"

services:

  worker:
    build:
      context: ./folder_worker
    image: wine_worker_image
    volumes:
      - ./folder_worker:/app
    command: python rpc_worker_async.py
    depends_on:
      - broker
      - rabbitmq
      - model
      - database
    env_file:
      - .env
    deploy:  # Enables scaling
      replicas: ${WORKER_REPLICAS:-1}
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: wine_rabbit
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"
      - "${RABBITMQ_UI_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  database:
    build:
      context: ./folder_database
    image: database_image
    container_name: database_container
    ports:
      - "${DATABASE_PORT:-8000}:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./folder_database:/app
    depends_on:
      - model
    env_file:
      - .env

  broker:
    build:
      context: ./folder_broker
    image: broker_image
    container_name: broker_container
    ports:
      - "${BROKER_PORT:-3000}:3000"
    command: uvicorn app:app --host 0.0.0.0 --reload --port 3000
    volumes:
      - ./folder_broker:/app
    depends_on:
      - database
      - model
    env_file:
      - .env

  model:
    build:
      context: ./folder_model
    image: model_server_image
    container_name: model_container
    ports:
      - "${MODEL_PORT:-5000}:5000"
    volumes:
      - ./folder_model:/app
    env_file:
      - .env
