version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis_2
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: wine_rabbit_2
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"
      - "${RABBITMQ_UI_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  database:
    build:
      context: ./folder_database
    image: database_image
    container_name: database_container_2
    ports:
      - "${DATABASE_PORT:-8000}:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./folder_database:/app
    # depends_on:
    #   - model
    env_file:
      - .env

  broker:
    build:
      context: ./folder_broker
    image: broker_image
    container_name: broker_container
    ports:
      - "${BROKER_PORT:-3000}:3000"
    command: uvicorn app:app --host 0.0.0.0 --reload --port 3000
    volumes:
      - ./folder_broker:/app
    depends_on:
      - rabbitmq
      - database
      - model
    env_file:
      - .env

  model:
    build:
      context: ./folder_model
    image: model_server_image
    container_name: model_container_2
    ports:
      - "${MODEL_PORT:-5000}:5000"
    volumes:
      - ./folder_model:/app
    env_file:
      - .env

  response_worker:
    build:
      context: ./folder_response_worker
    image: wine_response_worker
    command: python response_worker.py
    volumes:
      - ./folder_response_worker:/app
    # depends_on:
    #   - redis
    #   - rabbitmq
    env_file:
      - .env
    # restart: on-failure

  request_worker:
    build:
      context: ./folder_request_worker
    image: wine_request_worker_image
    container_name: request_worker
    volumes:
      - ./folder_request_worker:/app
    command: python request_worker.py
    # depends_on:
    #   - rabbitmq
    #   - model
    #   - database
    env_file:
      - .env
    deploy:
      replicas: ${WORKER_REPLICAS:-1}
